'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class _gResxRdlc
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources._gResxRdlc", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\Report\BP_AppForm_New2021.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pAppFormNewDITC() As String
            Get
                Return ResourceManager.GetString("pAppFormNewDITC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\Report\Appointment.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pAppointment() As String
            Get
                Return ResourceManager.GetString("pAppointment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\Report\Appointment_List.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pAppointmentList() As String
            Get
                Return ResourceManager.GetString("pAppointmentList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\Report\Appointment_Slip.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pAppointmentSlip() As String
            Get
                Return ResourceManager.GetString("pAppointmentSlip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PMIPS\PaySlipSheet.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property payslipReport() As String
            Get
                Return ResourceManager.GetString("payslipReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\Report\BillingTOP.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pBillingTOP() As String
            Get
                Return ResourceManager.GetString("pBillingTOP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\Report\BP_TOP_NEWBP_Oldversion.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pBillingTOPOldversion() As String
            Get
                Return ResourceManager.GetString("pBillingTOPOldversion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\Report\BP_TOP_2023.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pBP_TOP_2023() As String
            Get
                Return ResourceManager.GetString("pBP_TOP_2023", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\Report\eOR_BP2.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pEOR_BP2() As String
            Get
                Return ResourceManager.GetString("pEOR_BP2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\Report\eOR_RPT2.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pEOR_RPT2() As String
            Get
                Return ResourceManager.GetString("pEOR_RPT2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PMIPS\LeaveReport.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pLeaveReport() As String
            Get
                Return ResourceManager.GetString("pLeaveReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\Permit\Permit2.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pPermit2() As String
            Get
                Return ResourceManager.GetString("pPermit2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\_oRdlc_pPrintBusinessPayment.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pPrintBusinessPayment() As String
            Get
                Return ResourceManager.GetString("pPrintBusinessPayment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\_oRdlc_pPrintORCorporation.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pPrintCorporationOR() As String
            Get
                Return ResourceManager.GetString("pPrintCorporationOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\_oRdlc_pPrintGeneralCollection.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pPrintGeneralCollection() As String
            Get
                Return ResourceManager.GetString("pPrintGeneralCollection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\_oRdlc_pPrintORIndividual.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pPrintIndividualOR() As String
            Get
                Return ResourceManager.GetString("pPrintIndividualOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\Report\BP_ApplicationForm_NEW.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pReportAppForm_New() As String
            Get
                Return ResourceManager.GetString("pReportAppForm_New", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\Report\ApplicationForm.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pReportApplicationInfo() As String
            Get
                Return ResourceManager.GetString("pReportApplicationInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PMIPS\DailyTimeRecordReport.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pReportDTR() As String
            Get
                Return ResourceManager.GetString("pReportDTR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\Report\EnvelopeSeal.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pReportEnvelopeSeal() As String
            Get
                Return ResourceManager.GetString("pReportEnvelopeSeal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WebPortal\Report\_oRdlc_TransactionReport.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property pTransactionReport() As String
            Get
                Return ResourceManager.GetString("pTransactionReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PMIPS\PersonalDataSheet.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property _oRdlcPDS() As String
            Get
                Return ResourceManager.GetString("_oRdlcPDS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VS2014.RPTIMS\Report1.rdlc.
        '''</summary>
        Friend Shared ReadOnly Property _pReportBilling() As String
            Get
                Return ResourceManager.GetString("_pReportBilling", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
