'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BPLONewBP_ForApproval

    '''<summary>
    '''_oLabelSnackbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLabelSnackbargreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbargreen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''td_ApplicationNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_ApplicationNo As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_AcctNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_AcctNo As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_OwnershipType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_OwnershipType As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_DtiSecCda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_DtiSecCda As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_TIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_TIN As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_BusinessName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_BusinessName As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_MainOfficeAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_MainOfficeAddress As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_TelNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_TelNo As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_MobileNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_MobileNo As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_EmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_EmailAddress As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_OwnerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_OwnerName As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_Nationality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_Nationality As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_Area control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_Area As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FloorArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FloorArea As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_MaleEmpNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_MaleEmpNo As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FemaleEmpNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FemaleEmpNo As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_ResidingEmpNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_ResidingEmpNo As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_VanTruckNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_VanTruckNo As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_MotorNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_MotorNo As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_BusinessLocationAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_BusinessLocationAddress As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_Capital control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_Capital As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_Nature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_Nature As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''NatureHTML control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NatureHTML As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''td_FileName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileName1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileData1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileData1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileType1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileType1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileRemarks1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileRemarks1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileStatus1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileStatus1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileName2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileData2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileData2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileType2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileType2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileRemarks2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileRemarks2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileStatus2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileStatus2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileName3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileName3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileData3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileData3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileType3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileType3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileRemarks3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileRemarks3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileStatus3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileStatus3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileName4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileName4 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileData4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileData4 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileType4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileType4 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileRemarks4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileRemarks4 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileStatus4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileStatus4 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileName5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileName5 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileData5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileData5 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileType5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileType5 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileRemarks5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileRemarks5 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileStatus5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileStatus5 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileName6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileName6 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileData6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileData6 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileType6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileType6 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileRemarks6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileRemarks6 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_FileStatus6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_FileStatus6 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''_oGridViewBusLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oGridViewBusLine As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridViewTOP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewTOP As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''TotAmtDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TotAmtDue As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btn_TOP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_TOP As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnApproveForBilling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApproveForBilling As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''hdnCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCode As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnAppID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAppID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''err control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
