'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BPLTIMSBusinessLine

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''_oLabelSnackbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLabelSnackbargreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbargreen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_otextBusinessNature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otextBusinessNature As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTxtSearchBusLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtSearchBusLine As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oBtnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnSearch As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''cmbBusCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbBusCode As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otextArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otextArea As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_otextCapital control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otextCapital As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveBusLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveBusLine As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_oGridViewAddedBusline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oGridViewAddedBusline As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oPanelProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPanelProcess As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label72 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label72 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLabelFeeType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelFeeType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oPanel_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPanel_Ask As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oPanel1_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPanel1_Ask As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oLabel1_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabel1_Ask As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oTextBox1_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox1_Ask As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oPanel2_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPanel2_Ask As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oLabel2_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabel2_Ask As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oTextBox2_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox2_Ask As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oPanel3_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPanel3_Ask As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oLabel3_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabel3_Ask As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oTextBox3_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox3_Ask As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oPanel4_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPanel4_Ask As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oLabel4_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabel4_Ask As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oTextBox4_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox4_Ask As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oPanel5_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPanel5_Ask As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oLabel5_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabel5_Ask As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oTextBox5_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox5_Ask As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oPanel6_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPanel6_Ask As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oLabel6_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabel6_Ask As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oTextBox6_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox6_Ask As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oPanel7_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPanel7_Ask As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oLabel7_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabel7_Ask As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oTextBox7_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox7_Ask As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oPanel8_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPanel8_Ask As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oLabel8_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabel8_Ask As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oTextBox8_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox8_Ask As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oPanel9_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPanel9_Ask As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oLabel9_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabel9_Ask As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oTextBox9_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox9_Ask As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oPanel10_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPanel10_Ask As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oLabel10_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabel10_Ask As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oTextBox10_Ask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox10_Ask As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oPanel_oGridViewOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPanel_oGridViewOption As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oGridViewOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oGridViewOption As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Panel120 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel120 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oButton_OK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oButton_OK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''_oButtonTaxSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oButtonTaxSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Finish_End control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Finish_End As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_oRpt_EnvelopeSeal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oRpt_EnvelopeSeal As Global.Microsoft.Reporting.WebForms.ReportViewer
End Class
