'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BPLTIMS_NewBusinessLine

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''_oLabelSnackbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLabelSnackbargreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbargreen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLabelAcctNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelAcctNo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oLabelBussinessName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelBussinessName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oDDL_Category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oDDL_Category As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_oBtnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnSave As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_oGridViewBusinessDetailsNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oGridViewBusinessDetailsNew As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_otextBusinessNature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otextBusinessNature As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oBtnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnSubmit As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
