'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BPOtherTransaction

    '''<summary>
    '''_oLblBusID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusOwner As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusCategory1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusCategory1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oBtnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnCancel As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''_oBtnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnNext As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''_oSelectReferenceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oSelectReferenceNo As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_oSelectPaymentChannel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oSelectPaymentChannel As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_oTextOR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextOR As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oBtnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnSubmit As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''radioValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radioValue As Global.System.Web.UI.WebControls.HiddenField
End Class
