'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BusApplicationSummary

    '''<summary>
    '''S1_Ownershiptype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S1_Ownershiptype As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S1_IsRented control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S1_IsRented As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S2_DateRented control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S2_DateRented As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S2_RentPerMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S2_RentPerMonth As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S2_FName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S2_FName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S2_LName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S2_LName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S2_Brgy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S2_Brgy As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S2_Street control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S2_Street As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S2_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S2_Address As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S2_TelNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S2_TelNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S2_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S2_Email As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S2_Administrator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S2_Administrator As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S3_OwnerIMG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S3_OwnerIMG As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S3_EstablishmentIMG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S3_EstablishmentIMG As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S3_MapIMG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S3_MapIMG As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S4_OwnerIMG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S4_OwnerIMG As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Slide_End_frmCDA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Slide_End_frmCDA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''S5_CDA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_CDA As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S5_CDA2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_CDA2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Slide_End_frmDTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Slide_End_frmDTI As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''S5_DTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_DTI As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S5_DTI2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_DTI2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Slide_End_frmSEC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Slide_End_frmSEC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''S5_SEC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_SEC As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S5_SEC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_SEC2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S5_TIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_TIN As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S5_TIN2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_TIN2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S5_SSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_SSS As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S5_SSS2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_SSS2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S5_Brgy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_Brgy As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S5_Brgy2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_Brgy2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S5_CTC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_CTC As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S5_CTC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_CTC2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S5_CTCPlace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_CTCPlace As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S5_CTCPlace2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_CTCPlace2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S5_BIR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_BIR As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S5_BIR2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S5_BIR2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S6_DateEstablished control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S6_DateEstablished As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S6_Branch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S6_Branch As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S6_TradeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S6_TradeName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S6_NoMale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S6_NoMale As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S6_NoFemale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S6_NoFemale As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S6_NoLGU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S6_NoLGU As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S7_Brgy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S7_Brgy As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S7_DistCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S7_DistCode As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''S7_Brgy_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S7_Brgy_code As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''S7_Street control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S7_Street As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S7_Street_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S7_Street_code As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''S7_GrpBlg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S7_GrpBlg As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S7_StickerNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S7_StickerNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S7_PlateNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S7_PlateNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S7_StallNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S7_StallNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S7_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S7_Address As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''S8_Lname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S8_Lname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S8_Fname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S8_Fname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S8_Mname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S8_Mname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S8_Suffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S8_Suffix As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S8_Gender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S8_Gender As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S8_Citizenship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S8_Citizenship As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S8_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S8_Address As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''S8_TelNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S8_TelNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S8_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S8_Email As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''S8_AlternateEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S8_AlternateEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Confirm_12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Confirm_12 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_oLabelSnackbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbar As Global.System.Web.UI.WebControls.Label
End Class
