'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BusinessRenewalTaxPayer

    '''<summary>
    '''_oLabelSnackbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLabelSnackbargreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbargreen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusOwner As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusCategory1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusCategory1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusOwnership control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusOwnership As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_GVBusinessLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _GVBusinessLine As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_oLblTypeTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblTypeTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oPnFile1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPnFile1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oTxtFile1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtFile1 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oLblFile1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblFile1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oPnFile2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPnFile2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oTxtFile2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtFile2 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oLblFile2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblFile2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oPnFile3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPnFile3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oTxtFile3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtFile3 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oLblFile3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblFile3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oPnFile4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPnFile4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oTxtFile4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtFile4 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oLblFile4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblFile4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oPnFile5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPnFile5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oTxtFile5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtFile5 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oLblFile5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblFile5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oPnFile6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPnFile6 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oTxtFile6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtFile6 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oLblFile6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblFile6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oPnFile7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPnFile7 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oTxtFile7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtFile7 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oLblFile7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblFile7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oPnFile8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPnFile8 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oTxtFile8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtFile8 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oLblFile8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblFile8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oPnFile9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPnFile9 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oTxtFile9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtFile9 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oLblFile9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblFile9 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oPnFile10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPnFile10 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oTxtFile10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtFile10 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oLblFile10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblFile10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oPnFile11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPnFile11 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oTxtFile11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtFile11 As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oLblFile11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblFile11 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_opnlAllAskHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _opnlAllAskHeading As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_opnlTextAskQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _opnlTextAskQ As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_opnlDrpDownAskOpt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _opnlDrpDownAskOpt As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oListBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oListBox1 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cmb_MOP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_MOP As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_obtnPrintApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _obtnPrintApplication As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_oBtnOkay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnOkay As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
