'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BusinessRenewalPayment2

    '''<summary>
    '''_err control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _err As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''_oLabelSnackbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLabelSnackbargreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbargreen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oTextRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextRemarks As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''btnDecline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDecline As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''_oLblBusID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusOwner As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusOwnership control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusOwnership As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_GVBusinessLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _GVBusinessLine As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''div_SubmittedRequirements control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_SubmittedRequirements As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_GVRequirements control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _GVRequirements As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblPeriodCovered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeriodCovered As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMOP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMOP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div_TOP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_TOP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GridViewTOP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewTOP As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''trCTC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCTC As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblCTCAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCTCAmount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TotAmtDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TotAmtDue As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GrandTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrandTotal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div_PaymentFound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_PaymentFound As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btn_AppForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_AppForm As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btn_TOP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_TOP As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnPayNow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPayNow As Global.System.Web.UI.HtmlControls.HtmlInputButton
End Class
