'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BusLessorInfo

    '''<summary>
    '''Slide_02_DateRented control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Slide_02_DateRented As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Slide_02_DateRented_Formatted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Slide_02_DateRented_Formatted As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''Slide_02_RentPerMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Slide_02_RentPerMonth As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Slide_02_LessorFname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Slide_02_LessorFname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Slide_02_LessorLname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Slide_02_LessorLname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Slide_02_Brgy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Slide_02_Brgy As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Slide_02_Street control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Slide_02_Street As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Slide_02_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Slide_02_Address As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''Slide_02_TelNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Slide_02_TelNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Slide_02_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Slide_02_Email As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Slide_02_Administrator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Slide_02_Administrator As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''_oLabelSnackbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLabelSnackbargreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbargreen As Global.System.Web.UI.WebControls.Label
End Class
