'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BusOwnershipType

    '''<summary>
    '''Slide_01_OwnershipType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Slide_01_OwnershipType As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''radio1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio1 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''radio2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio2 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''SelectedYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedYesNo As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SelectedOwnership control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedOwnership As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''_oLabelSnackbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLabelSnackbargreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbargreen As Global.System.Web.UI.WebControls.Label
End Class
