'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CedulaPage

    '''<summary>
    '''CedulaIndi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CedulaIndi As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''CedulaCorp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CedulaCorp As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''chkSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSelect As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''_oTxtFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtFirstName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtMiddleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtMiddleName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtLastName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtAddress As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''radCitizenship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radCitizenship As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_oTxtBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtBirthDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtBirthPlace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtBirthPlace As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''radGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radGender As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''radCivilstat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radCivilstat As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''radProfession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radProfession As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''_oTxtTIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtTIN As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtHeight As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtWeight As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtBusinessIncome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtBusinessIncome As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtSalary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtSalary As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtPropertySale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtPropertySale As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''AmountToPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AmountToPay As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtHiddenAmountDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtHiddenAmountDue As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''_oTxtHiddenPenalty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtHiddenPenalty As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''_oPayLayter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPayLayter As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_oPayNow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oPayNow As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
