'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DepartmentSetup

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''_oLabelSnackbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLabelSnackbargreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbargreen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gv_Department control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_Department As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''hdnDept2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDept2 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''_ohdnAppType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _ohdnAppType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''_ohdnAppType2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _ohdnAppType2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''test1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents test1 As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''Edit_DepartmentCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Edit_DepartmentCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Edit_Department control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Edit_Department As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Edit_Usertype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Edit_Usertype As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Edit_Regulatory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Edit_Regulatory As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''btnEditSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditSave As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''_oTxtDepartmentCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtDepartmentCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtDepartment As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtUsertype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtUsertype As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtRegulatory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtRegulatory As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_obtnProceed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _obtnProceed As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemove As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''hdnDepartmentCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDepartmentCode As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDepartment As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnUsertype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnUsertype As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnRegulatory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnRegulatory As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
