'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LGU_GeneralCollectionReportOLD

    '''<summary>
    '''ifchckall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifchckall As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''_oGridViewSPIDCPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oGridViewSPIDCPay As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_obtnProceed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _obtnProceed As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_oLblCountSPIDCPAY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblCountSPIDCPAY As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblTotalSPIDCPAY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblTotalSPIDCPAY As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oGridViewPostedSPIDCPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oGridViewPostedSPIDCPay As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_oLblCountPostedSPIDCPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblCountPostedSPIDCPay As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblTotalPostedSPIDCPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblTotalPostedSPIDCPay As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oGridViewUnpaidLandBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oGridViewUnpaidLandBank As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_oBtnProceedLBP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnProceedLBP As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_oLblCountLandBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblCountLandBank As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblTotalLandBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblTotalLandBank As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oGridViewPostedLandBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oGridViewPostedLandBank As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_oLblCountPostedLandBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblCountPostedLandBank As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblTotalPostedLandBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblTotalPostedLandBank As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oGridViewUnpaidDBP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oGridViewUnpaidDBP As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button2 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_oLblCountUnpaidDBP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblCountUnpaidDBP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblTotalUnpaidDBP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblTotalUnpaidDBP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oGridViewPostedDBP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oGridViewPostedDBP As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_oLblCountPostedDBP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblCountPostedDBP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblTotalPostedDBP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblTotalPostedDBP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oBtnPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnPrint As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''_oMSRV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oMSRV As Global.Microsoft.Reporting.WebForms.ReportViewer

    '''<summary>
    '''_oLBLCOUNTALL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLBLCOUNTALL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLBLGrandTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLBLGrandTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''actid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actid As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ButtonValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonValue As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
