'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LGU_OPL

    '''<summary>
    '''lblWSPREFNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWSPREFNO As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGatewaySelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGatewaySelected As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGatewayRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGatewayRefNo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnPostAnyway control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPostAnyway As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDone As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''cmbSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSearch As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''txtSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearch As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''cmbGateWay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbGateWay As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''cmbType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbType As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''txtDateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateFrom As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateTo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cmbStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbStatus As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''cmbSortBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSortBy As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''cmbOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbOrder As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''btnFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFilter As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''gv_paymentList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_paymentList As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_oBtnPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnPrint As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''_oMSRV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oMSRV As Global.Microsoft.Reporting.WebForms.ReportViewer

    '''<summary>
    '''Report_EOR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Report_EOR As Global.Microsoft.Reporting.WebForms.ReportViewer

    '''<summary>
    '''actid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actid As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ButtonValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonValue As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''err control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnErr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnErr As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnErr2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnErr2 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnErr3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnErr3 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnTxnRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTxnRefNo As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnGateWay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnGateWay As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnTDN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTDN As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''btnInquire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInquire As Global.System.Web.UI.HtmlControls.HtmlInputButton
End Class
