'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Miscellaneous

    '''<summary>
    '''_oSelectCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oSelectCategory As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_oSelectSpecific control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oSelectSpecific As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_oLabelTotalAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelTotalAmount As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
