'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewBP_Regulatory

    '''<summary>
    '''_oLabelSnackbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLabelSnackbargreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbargreen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_AppNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_AppNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt_BusTradeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BusTradeName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt_BusAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BusAddress As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt_Brgy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Brgy As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''BRGY_LOCK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BRGY_LOCK As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BRGY_ClearanceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BRGY_ClearanceNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtBrgy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBrgy As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Grid_BRGY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_BRGY As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BRGY_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BRGY_Status As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''BRGY_Remarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BRGY_Remarks As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btn_BRGY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_BRGY As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''CPDO_LOCK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CPDO_LOCK As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CPDO_ClearanceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CPDO_ClearanceNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CPDO_Info1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CPDO_Info1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CPDO_Info2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CPDO_Info2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CPDO_Info3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CPDO_Info3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CPDO_Info4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CPDO_Info4 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CPDO_Info5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CPDO_Info5 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Grid_CPDO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_CPDO As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''CPDO_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CPDO_Status As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CPDO_Remarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CPDO_Remarks As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btn_CPDO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_CPDO As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''div_BLDG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_BLDG As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BLDG_LOCK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BLDG_LOCK As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BLDG_ClearanceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BLDG_ClearanceNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''BLDG_Info1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BLDG_Info1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''BLDG_Info2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BLDG_Info2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''BLDG_Info3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BLDG_Info3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''BLDG_Info4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BLDG_Info4 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''BLDG_Info5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BLDG_Info5 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Grid_BLDG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_BLDG As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BLDG_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BLDG_Status As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''BLDG_Remarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BLDG_Remarks As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btn_BLDG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_BLDG As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''div_HO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_HO As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HO_LOCK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HO_LOCK As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HO_ClearanceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HO_ClearanceNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''HO_Info1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HO_Info1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''HO_Info2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HO_Info2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''HO_Info3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HO_Info3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''HO_Info4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HO_Info4 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''HO_Info5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HO_Info5 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Grid_HO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_HO As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''HO_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HO_Status As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''HO_Remarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HO_Remarks As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btn_HO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_HO As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''div_CENRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_CENRO As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CENRO_LOCK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CENRO_LOCK As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CENRO_ClearanceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CENRO_ClearanceNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CENRO_Info1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CENRO_Info1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CENRO_Info2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CENRO_Info2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CENRO_Info3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CENRO_Info3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CENRO_Info4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CENRO_Info4 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CENRO_Info5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CENRO_Info5 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Grid_CENRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_CENRO As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''CENRO_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CENRO_Status As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CENRO_Remarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CENRO_Remarks As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btn_CENRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_CENRO As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''div_FIRE2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_FIRE2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''FIRE_LOCK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FIRE_LOCK As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''FIRE_ClearanceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FIRE_ClearanceNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''FIRE_Info1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FIRE_Info1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''FIRE_Info2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FIRE_Info2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''FIRE_Info3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FIRE_Info3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''FIRE_Info4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FIRE_Info4 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''FIRE_Info5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FIRE_Info5 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Grid_FIRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_FIRE As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''FIRE_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FIRE_Status As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''FIRE_Remarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FIRE_Remarks As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btn_FIRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_FIRE As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''GridRegulatory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridRegulatory As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''hdnCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCode As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnAppID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAppID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
