'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewBusiness

    '''<summary>
    '''_oDpTypeofOwnership control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oDpTypeofOwnership As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxtDateApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtDateApplication As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''_oTxtHdnTab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtHdnTab1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''_oTxtHdnTab2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtHdnTab2 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''_otxtBusName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtBusName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTradeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTradeName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtBusAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtBusAddress As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''_otxtDTISECReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtDTISECReg As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtDTIDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtDTIDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtBusTelNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtBusTelNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtBusEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtBusEmailAddress As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''_otxtBusTIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtBusTIN As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTPLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTPLastName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTPFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTPFirstName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTPMiddleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTPMiddleName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTPSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTPSuffix As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oCBTPGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oCBTPGender As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxtTPAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTPAddress As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''_oCBTPCitizenship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oCBTPCitizenship As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxtTPTelNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTPTelNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTPEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTPEmailAddress As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''_otxtTPTIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTPTIN As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTPSSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTPSSS As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTP2LastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTP2LastName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTP2FirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTP2FirstName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTP2MiddleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTP2MiddleName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTP2Suffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTP2Suffix As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oCBTP2Gender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oCBTP2Gender As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxtTP2Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTP2Address As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''_oCBTP2Citizenship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oCBTP2Citizenship As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxtTP2TelNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTP2TelNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTP2EmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTP2EmailAddress As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''_otxtTP2TIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTP2TIN As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTP2SSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTP2SSS As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCorpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCorpName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCorpTelNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCorpTelNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCorpAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCorpAddress As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''_otxtCorpEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCorpEmailAddress As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''_otxtCorpPresident control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCorpPresident As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCPresEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCPresEmailAddress As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCPresMobileNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCPresMobileNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oCBCPresGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oCBCPresGender As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxtCTresName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCTresName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCTresEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCTresEmailAddress As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCTresMobileNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCTresMobileNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCTresGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCTresGender As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxtCSecName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCSecName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCSecEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCSecEmailAddress As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCSecMobileNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCSecMobileNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCSecGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCSecGender As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxtCManName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCManName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCManEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCManEmailAddress As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCManMobileNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCManMobileNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCManGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCManGender As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxtCRepName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCRepName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCRepEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCRepEmailAddress As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCRepMobileNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCRepMobileNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtCRepGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtCRepGender As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxtArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtArea As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTotNoCapital control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTotNoCapital As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTotMale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTotMale As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTotFemale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTotFemale As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtTotNoEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtTotNoEmployees As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_cbrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _cbrent As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''_otxtLessorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtLessorName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtLessorMobileNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtLessorMobileNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtLessorMonthlyRent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtLessorMonthlyRent As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtLessorAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtLessorAddress As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''_otxtLessorCitizenship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtLessorCitizenship As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxtLessorGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtLessorGender As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxtLessorTaxDec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtLessorTaxDec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtLessorBuildingNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtLessorBuildingNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtLessorEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtLessorEmail As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''_otxtBusHasDelivery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtBusHasDelivery As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxtBusBranchMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtBusBranchMain As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxtBusDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtBusDesc As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtBusImgCommodities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtBusImgCommodities As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_otxtBusImgLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtBusImgLoc As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_otxtBusImgID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtBusImgID As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_otxtRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtRemarks As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''_obtn_Subm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _obtn_Subm As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_otxtPickupStreetNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtPickupStreetNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxtPickupBarangay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtPickupBarangay As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''_otxtPickupDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtPickupDistrict As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''_otxtPickupMuniCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtPickupMuniCity As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''_otxtPickupProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxtPickupProvince As Global.System.Web.UI.WebControls.DropDownList
End Class
