'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewBusinessRenewal

    '''<summary>
    '''_oLabelSnackbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLabelSnackbargreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbargreen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusOwner As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLblBusCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblBusCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_GVBusinessLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _GVBusinessLine As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_opnlAllAskHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _opnlAllAskHeading As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_opnlTextAskQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _opnlTextAskQ As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_opnlDrpDownAskOpt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _opnlDrpDownAskOpt As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''_oListBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oListBox1 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''_obtnSaveEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _obtnSaveEdit As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
