'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewPropertyRequiredFiles

    '''<summary>
    '''_oTxtDeedofsale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtDeedofsale As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oTxtCopyofTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtCopyofTitle As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oTxtProofofPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtProofofPayment As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oTxtTaxClearance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtTaxClearance As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oTxtDeclarationCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtDeclarationCopy As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oTxtCorporateProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtCorporateProperty As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oTxtValidID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtValidID As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''_oBtnContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnContinue As Global.System.Web.UI.WebControls.Button
End Class
