'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewProperty

    '''<summary>
    '''_oLabelSnackbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLabelSnackbargreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbargreen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oTxtOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtOwner As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtOwnerAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtOwnerAddress As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''_oTxtAdministrator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtAdministrator As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtAdminAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtAdminAddress As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''_oTxtNoSt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtNoSt As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtBarangay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtBarangay As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtDistrict As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtCityMunicipality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtCityMunicipality As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtProvince As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtOCT_TCT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtOCT_TCT As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtSurveyNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtSurveyNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_TxtLotNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _TxtLotNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtBlockNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtBlockNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtArea As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtAmountSold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtAmountSold As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtAgricultural control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtAgricultural As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtResidentialArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtResidentialArea As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtCommercialArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtCommercialArea As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtMineral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtMineral As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtSpecial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtSpecial As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtTimberland control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtTimberland As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtIndustrial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtIndustrial As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtTotalArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtTotalArea As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oBtnContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnContinue As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
