'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PaymentInstruction

    '''<summary>
    '''td_TransactionType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_TransactionType As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_Amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_Amount As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_Description As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_AssessmentNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_AssessmentNo As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''td_OnlineID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents td_OnlineID As Global.System.Web.UI.HtmlControls.HtmlTableCell
End Class
