'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Register

    '''<summary>
    '''div_agent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_agent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TXTTRAPERROR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTTRAPERROR As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TXTTRAPERROR2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTTRAPERROR2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oCBResident control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oCBResident As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtLocalUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocalUserName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPassKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPassKey As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''testclick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents testclick As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''divCarousel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCarousel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgLogoHere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLogoHere As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''LoginEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoginEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''LoginPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoginPassword As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''_btnLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _btnLogin As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''txtLoginEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoginEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLoginPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoginPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSignIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSignIn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnForgot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnForgot As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gv_DLForms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_DLForms As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnResend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResend As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TNC_Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TNC_Title As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TNC_Content control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TNC_Content As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ANN_TITLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ANN_TITLE As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ANN_DATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ANN_DATE As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ANN_CONTENT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ANN_CONTENT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''OnlineNow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OnlineNow As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''err control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''testSnackBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents testSnackBar As Global.System.Web.UI.WebControls.Button
End Class
