'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StpBusinessPaymentSetup

    '''<summary>
    '''_oTextBox_Or_Number_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Or_Number_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Or_Number_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Or_Number_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Validation_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Validation_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Validation_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Validation_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Table_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Table_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Table_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Table_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_DateIssued_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_DateIssued_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_DateIssued_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_DateIssued_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_AmountInWord_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_AmountInWord_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_AmountInWord_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_AmountInWord_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
