'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StpCtcIndSetup

    '''<summary>
    '''_oTextBox_SRS_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_SRS_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_SRS_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_SRS_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_OrNumber_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_OrNumber_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_OrNumber_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_OrNumber_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Year_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Year_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Year_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Year_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_LguProfile_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_LguProfile_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_LguProfile_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_LguProfile_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_DateIssued_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_DateIssued_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_DateIssued_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_DateIssued_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_TIN_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_TIN_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_TIN_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_TIN_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_LastName_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_LastName_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_LastName_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_LastName_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_FirstName_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_FirstName_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_FirstName_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_FirstName_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_MiddleName_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_MiddleName_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_MiddleName_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_MiddleName_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Address_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Address_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Address_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Address_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Gender_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Gender_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Gender_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Gender_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Citizenship_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Citizenship_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Citizenship_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Citizenship_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_BirthPlace_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_BirthPlace_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_BirthPlace_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_BirthPlace_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Occupation_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Occupation_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Occupation_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Occupation_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_BasicAmount_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_BasicAmount_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_BasicAmount_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_BasicAmount_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_TaxAmount_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_TaxAmount_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_TaxAmount_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_TaxAmount_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Penalty_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Penalty_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_Penalty_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_Penalty_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_TotalAmount_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_TotalAmount_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_TotalAmount_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_TotalAmount_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_CivilStatus_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_CivilStatus_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_CivilStatus_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_CivilStatus_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_RPTIncome_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_RPTIncome_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_RPTIncome_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_RPTIncome_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_ProfIncome_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_ProfIncome_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_ProfIncome_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_ProfIncome_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_BusIncome_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_BusIncome_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_BusIncome_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_BusIncome_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_RPTIncomeComputation_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_RPTIncomeComputation_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_RPTIncomeComputation_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_RPTIncomeComputation_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_ProfIncomeComputation_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_ProfIncomeComputation_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_ProfIncomeComputation_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_ProfIncomeComputation_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_BusIncomeComputation_Top control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_BusIncomeComputation_Top As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oTextBox_BusIncomeComputation_Left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBox_BusIncomeComputation_Left As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
