'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TreasuryBusinessRenewalList

    '''<summary>
    '''_oTxtShowEntries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtShowEntries As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_oTxtShowEntriesHdn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtShowEntriesHdn As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''_oTxtSearchFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtSearchFilter As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_oHdnTopCounterKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oHdnTopCounterKey As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''_oHdnTopCounterAssess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oHdnTopCounterAssess As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''_oTxtSearchKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtSearchKey As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_oLblShowingValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblShowingValue As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oTtlEntries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTtlEntries As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oTxtShowEntriesAssess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtShowEntriesAssess As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_oTxtShowEntriesHdnAssess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtShowEntriesHdnAssess As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''_oTxtSearchFilterAssess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtSearchFilterAssess As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_oTxtSearchKeyAssess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtSearchKeyAssess As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''GridView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView2 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_oLblShowingValueAssess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLblShowingValueAssess As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oTtlEntriesAssess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTtlEntriesAssess As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
