'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserAccountManagementCU

    '''<summary>
    '''_obtn_Edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _obtn_Edit As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_otxt_EmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_EmailAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_otxt_Office control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_Office As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_otxt_UserLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_UserLevel As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxt_Lastname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_Lastname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_otxt_Firstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_Firstname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_otxt_Middlename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_Middlename As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_otxt_NameSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_NameSuffix As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_otxt_Birthdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_Birthdate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxt_BirthPlace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_BirthPlace As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''_otxt_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_Address As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''_otxt_Gender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_Gender As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxt_Citizenship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_Citizenship As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxt_CivilStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_CivilStatus As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_otxt_Profession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_Profession As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxt_TIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_TIN As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxt_Contact_Number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_Contact_Number As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxt_Contact_OtherNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_Contact_OtherNumber As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxt_Contact_Telephone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_Contact_Telephone As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxt_Height control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_Height As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_otxt_Weight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _otxt_Weight As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_obtn_Save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _obtn_Save As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_obtn_Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _obtn_Cancel As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
