'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LBP_EPS

    '''<summary>
    '''PerformEcho_Input control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PerformEcho_Input As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''PostPayments_trxnamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostPayments_trxnamt As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''PostPayments_merchantcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostPayments_merchantcode As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''PostPayments_bankcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostPayments_bankcode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''PostPayments_trxndetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostPayments_trxndetails As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''PostPayments_trandetail1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostPayments_trandetail1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''PostPayments_trandetail2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostPayments_trandetail2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''PostPayments_trandetail3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostPayments_trandetail3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''PostPayments_trandetail4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostPayments_trandetail4 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''PostPayments_trandetail5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostPayments_trandetail5 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''PostPayments_username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostPayments_username As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''PostPayments_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostPayments_password As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''PostPayments_secretKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostPayments_secretKey As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btn_Submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Submit As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''txt_Result control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Result As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hdn_transaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_transaction As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
