'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RPTIMSCertification

    '''<summary>
    '''_oGridViewRequestStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oGridViewRequestStatus As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''cmbRPTAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbRPTAccount As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''cmbCertifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCertifications As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''txtSelectedRPT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSelectedRPT As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtSelectedRPTName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSelectedRPTName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtSelectedCertificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSelectedCertificate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtSelectedCertificateName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSelectedCertificateName As Global.System.Web.UI.HtmlControls.HtmlInputText
End Class
