'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RPTIMSAssessmentBilling

    '''<summary>
    '''_oLabelSnackbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLabelSnackbargreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbargreen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Slide_01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Slide_01 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RPTSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RPTSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oGridViewRPT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oGridViewRPT As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_oTextBoxTDN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBoxTDN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdnFldSelectedValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFldSelectedValues As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SelectedAcctNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedAcctNo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''_oTextBoxBillingDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBoxBillingDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RadioQtr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioQtr1 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''RadioQtr2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioQtr2 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''RadioQtr3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioQtr3 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''RadioQtr4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioQtr4 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

    '''<summary>
    '''_oTextBoxYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTextBoxYear As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''_oGridViewBillingTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oGridViewBillingTemp As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_oMSRV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oMSRV As Global.Microsoft.Reporting.WebForms.ReportViewer
End Class
